_target_: byu.loss.monai_tversky.TverskyLoss

include_background: True
to_onehot_y: False
sigmoid: True
softmax: False
other_act: null
alpha: 0.5
beta: 0.5
reduction: mean
smooth_nr: 1e-2
smooth_dr: 1e-2
batch: False
soft_label: True