# Dataloader related configs

defaults:
  - sampler: null

steps_per_epoch: -1 # -1 means interpolated from dataset's length
train_batch_size: ???
val_batch_size: ${loader.train_batch_size}
num_workers: 8
pytorch_num_threads: null
pin_memory: True
drop_last: True
persistent_workers: False
batch_sampler: null