# @package _global_

hydra:
  job:
    env_set: # auto export environment vars
      TIMM_USE_OLD_CACHE: 1
      # WANDB_BASE_URL: http://172.16.2.55:8955
      NO_ALBUMENTATIONS_UPDATE: 1
      PL_FAULT_TOLERANT_TRAINING: 0
      # HF_HUB_OFFLINE: "True"
      POLARS_ALLOW_FORKING_THREAD: 1