defaults:
  - encoder: 2d_maxvit

_target_: byu.models.unet_2d.Unet2dModel

num_kpts: 1

neck:
    name: factorized_fpn
    intermediate_channels_list: 64
    target_level: -2
    conv_ksizes: [3, 3]
    norm: layernorm_2d
    act: gelu
    interpolation_mode: bilinear

decoder:
    n_blocks: 1
    channels: [256, 192, 128, 96, 64]
    dropout: 0.0
    out_channels: 1
    act: sigmoid

reg_head:
    enable: True
    type: decoupled_v2
    feature_mode: enc_dec
    feature_idx: -1
    hidden_dim: 1024
    hidden_act: gelu
    hidden_first_dropout: 0.0
    cls_dropout: 0.0
    reg_dropout: 0.0
    norm: layernorm2d
    norm_eps: 1e-6
    pool_type: avg  # type=decoupled only
    hidden_size_per_kpt: 64  # type=decoupled_v2 only

dsnt:
    enable: True