_target_: byu.models.unet_3d.Unet3dModel

defaults:
  - encoder: 3d_smp

decoder:
  # decoder_channels: [192, 96, 64, 48, 32]
  decoder_channels: [192, 96, 48]  # /16
  n_blocks: 1
  use_batchnorm: True
  attention_type: scse
  center: False
  strides: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  weight_init: xavier

head:
  # multiscale indices, where the first will be used in eval/predict phase
  ms: [0] 
  out_channels: 1
  weight_init: xavier
