_target_: byu.models.swinunetr.SwinUNETR

img_size: ${data.patch_size}
in_channels: 1
out_channels: ${data.num_particles}
depths: [2, 2, 2, 2]
num_heads: [3, 6, 12, 24]
feature_size: 24
norm_name: instance
drop_rate: 0.0
attn_drop_rate: 0.0
dropout_path_rate: 0.0
normalize: True
use_checkpoint: False
spatial_dims: 3
downsample: merging
use_v2: False

pretrained: ckpts/ssl_pretrained_weights.pth