model_name: swinv2_tiny_window16_256.ms_in1k # swinv2_tiny_window8_256.ms_in1k | swinv2_tiny_window16_256.ms_in1k
pretrained: True
img_size:
- ${data.patch_size.1}
- ${data.patch_size.2}
in_chans: ${data.patch_size.0}
num_classes: 0
drop_rate: 0.0
drop_path_rate: 0.0
strict_img_size: False