_target_: byu.models.encoders.cnn_lstm.CnnLstmEncoder
        
resample:
    stride: 2
    channels: 3
    
normalize: model
    
encoder_2d:        
    model_name: convnext_nano.r384_ad_in12k  # convnext_tiny.fb_in22k_ft_in1k_384
    pretrained: True
    feature_indices: [0, 1, 2, 3]
    features_only: False
    in_chans: ${model.encoder.resample.channels}
    drop_rate: 0.0
    drop_path_rate: 0.0

downsample:
    mode: avg_pool
    strides: [2, 2, 2, 2]

lstm:
    enable: False
    idxs: [0, 1, 2, 3]
    bi: True
    num_layers: 1