# @package _global_

defaults:
  - 3d_base_heatmap
  - override /model: 3d_unet_r50_tsn
  - _self_

model:
  encoder:
    resample_stride: 2

trainer:
  deterministic: False

tags: ["heatmap", "unet", "r50-tsn", "beta"]
exp_name: unet_r50-tsn_beta



